### ISSUE TITLE
Simplify using event body in jinja

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#410]
I almost died writing this code 😅 :

```jinja
{% macro flatten(fields, ns, depth) %}
  {% if fields %}
    {% for f in fields | sort(attribute="id") %}
      {% set ns.flat = [ns.flat, [{'field':f,'depth':depth}]] | flatten %}
        {% if f.fields %}
          {% set _= flatten(f.fields, ns, depth + 1) %}
        {% endif %}
    {% endfor %}
  {% endif %}
{% endmacro %}
...

{% set ns = namespace(flat=[])%}{% set _ = flatten(fields, ns, 0) %}
```

which flattens event body definition to render it in a table. 

Code-generation might have some other needs, but at least for markdown generation, it would be awesome to have a helper written  in some real language.

Huge tanks to @jsuereth for his suggestion here https://github.com/open-telemetry/semantic-conventions/pull/1464/files#r1796899825 to add a custom filter that's do something like 

`{% for field, depth in fields | sort_by_body_field_depth %}`

**Comment by lquerel** [comment]
@lmolkova and @jsuereth

I’m thinking about adding the following Jinja filter:

```jinja
{% for path, field, depth in body|body_fields %}
    Do something with {{ field }} at depth {{ depth }} with path {{ path }}
{% endfor %}
```

In comparison with the initial proposal, I’ve made a few additions:
- **path**: I added a path parameter to the for loop expr because I suspect a fully qualified path will be useful in some contexts. It's also not easy to maintain this on the Jinja side.
- **leaf_only**: Added a boolean argument `leaf_only` to specify if we want only leaf nodes or intermediary levels as well (with the default being false).
- **traverse_mode**: Introduced a `traverse_mode` argument, which can be either `dfs` or`bfs` (with the default being dfs).
- **attribute**: Added an `attribute` argument to specify the object attribute used to sort the fields (defaulting to id). Note that the term attribute aligns with existing Jinja filters such as sort.

More complex example:
```jinja
{% for path, field, depth in body|body_fields(leaf_only=true, traverse_mode="bfs", attribute="type") %}
    Do something with {{ field }} at depth {{ depth }} with path {{ path }}
{% endfor %}
```

Please let me know if anything is missing or if you have suggestions!
